version: '3.9'

services: 
  nginx: 
    image: nginx:1.21.6-alpine
    container_name: nginx
    depends_on:
      - tht
    ports:
      - "3333:80"
    volumes: 
     -  ./lar-data:/usr/share/lar-data
    networks: 
      - lar-webscraping

  tht:
    build: .
    container_name: tht
    volumes: 
     -  .:/usr/lar-webscraping
    networks: 
      - lar-webscraping

networks: 
  lar-webscraping: 
    driver: bridge
